include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener input-split-listener torabo-trackpad-live-split torabo-caps torabo-rpc-tunnel torabo-timing torabo-trackball torabo-macros torabo-reserved-layers"
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DTORABO_RESERVED_LAYERS=6"
    artifact-name: torabo_tsuki_lp_right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "studio-rpc-usb-uart input-trackpad-mini input-split torabo-timing-split"
    artifact-name: torabo_tsuki_lp_left_peripheral
  - board: bmp_boost
    shield: settings_reset
